image: eclipse-temurin:17-jdk-alpine

stages:
  - build
  - deploy

variables:
  GRADLE_USER_HOME: ".gradle-cache"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle-cache/

build:
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/**
    expire_in: 1 day

deploy:
  stage: deploy
  cache: []
  needs:
    - build
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy
  only:
    - main